name: mdns
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - tqdm
  - einops
  - huggingface_hub
  - omegaconf
  - pyyaml
  - pip
  - pip:
      - timm
      - notebook
      - wandb
      - ase=3.24.0
      - clease=1.1.0
      - icet=3.1

